# Podcast Settings
title: Ollie Talking Shit
subtitle: Sporadic recordings of Ollie learning to talk.
summary: Sporadic recordings of Ollie learning to talk.
owner: Andy Taylor
email: hi@andytaylor.me
copyright_year: 2015
keywords: kid,learning,talking,australian
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ollietalkingshit.andytaylor.me/" # the base hostname & protocol for your site
itunes_category_one: "Kids &amp; Family"
itunes_category_two: "Education"
itunes_category_three: "Comedy"
colour: "#610fdd"

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["*.psd", "CNAME", "README.md"]
